---
title: "Resources"
---

Please use the blavaan discussion group for all questions/issues related to blavaan.  This can be found at

<a target="_blank" href="https://groups.google.com/d/forum/blavaan">https://groups.google.com/d/forum/blavaan</a><br /><br />

Other resources are listed below:

- The <a href="http://lavaan.ugent.be/resources/index.html">lavaan resources page</a> is helpful for model specification examples; it is mostly the same specification that is used in blavaan, and the main blavaan commands just add the letter "b" to the start of the main lavaan commands.

- "Getting started with blavaan" materials by Rens van de Schoot and colleagues: <a href="https://www.rensvandeschoot.com/tutorials/blavaan-how-to-get-started/">html</a>

- A Stan case study on *blavaan*, by Feng Ji and colleagues: <a href="https://mc-stan.org/users/documentation/case-studies/sem.html">html</a>

- Many recorded presentations are available on the internet:
    - The longest talk with the most details: <a href="https://youtu.be/xJy5zIkzgvg">Presentation to the Oslo UseR Group,</a> including real-time coding examples near the end. (Code from those examples is <a href="https://ecmerkle.github.io/pub/merkle_oslo_script.R">here.</a>)

    - Details about how the package works: <a href="https://www.youtube.com/watch?v=Mm6oP_Ss6qg">A virtual presentation</a> to the <a href="https://www.psychoco.org/2022/">2022 International Workshop on Psychometric Computing.</a>

    - Basic overview of the package: <a href="https://www.youtube.com/watch?v=zWA43-6taNA">useR! 2020 virtual presentation</a> (done early in the pandemic, and demonstrating the author's poor video editing skills.)

- Slides from an <a href="https://ecmerkle.github.io/pub/Merkle_msu21.pdf">hour-long seminar presentation</a> to the Michigan State Methods Group, October, 2021.

- Slides (blavaan and others) from a <a href="https://osf.io/bcy78/">symposium on the lavaan ecosystem</a> at the 2019 International Meeting of the Psychometric Society, Santiago, Chile.
